FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copia tudo do repositório
COPY . .

# Entra na pasta onde você colocou o Maven e o código
WORKDIR /app/fitshake_back_end

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

EXPOSE 8080

# Copia o JAR gerado dentro da subpasta target do backend
COPY --from=build /app/fitshake_back_end/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]