# Estágio 1: Build da aplicação
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copia tudo o que está na pasta atual (onde o Dockerfile está) para dentro de /app
COPY . .

# Executa o build direto, pois o pom.xml já vai estar na raiz /app
RUN mvn clean package -DskipTests

# Estágio 2: Execução do Java
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

EXPOSE 8080

# Copia o JAR gerado no estágio anterior
COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]